apiVersion: apps/v1
kind: Deployment
metadata:
  name: s4app-deployment
  labels:
    app: s4app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s4app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: s4app
    spec:
      containers:
      - name: simple-flask
        # image: IMAGE_TAG
        image: giftxxvi/s4app
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 8080
